### ISSUE TITLE
Color Support

### ISSUE THREAD

**Issue by khushal-banks** [khushal-banks/log-libc#8]
One thing you could do, if interested, is adding color support for when the output is a terminal. 
It is possible to use ANSI escape codes, which won't work on some terminals (notably, classic Windows Console, but they work in Windows Terminal.

NOTE: You can check for a WT_SESSION environment variable to ensure you're inside the correct windows terminal)

Current Plan:
1. Print on stdout/stderr with colors
2. Assign one color to each log-level
3. Enable/Disable colors using log_init function, so that it can be controlled at run-time.

I would add this at some point for at least Linux, hopefully, when i want to see ERROR in color red, WARNING in yellow

**Comment by jgabaut** [comment]
Hi, I gave this suggestion and I'd like to provide some input on how I'd do it.

I leave a reference to my library, if you want to check out the color management is done.

The `WT_SESSION` part was just a trick I found online, but it works in a pinch to avoid bothering with the logic for color printing when the terminal doesn't support the escapes.

[spuro - Free C log library](https://github.com/jgabaut/spuro)

I could provide help if needed, but the first thing to do would be to define how to refactor the main signatures to take the color.

When you're happy and set with how you'd like to define that, I'm available to implement this.

**Comment by khushal-banks** [comment]
To be honest, I personally wanted to not work on this. But now as you have shared a code, i am desperate to add this feature. Thank you for offering help, If nothing goes wrong, i would update you within two-three days.

**Comment by jgabaut** [comment]
@khushal-banks One thing I'd like to ask is the license for this library, since it didn't come up for me anywhere...

My code is on GPL-3.0, and I'd be happy to also cook up a compatibility layer between the two log function interfaces, if the licenses were to be compatible. :)

**Comment by khushal-banks** [comment]
There is no license for log-libc. It's available for free use, fork, share, customize and doing whatever one may wish to do with this. I don't know which license cover that. I did checkout GPL-3.0, which is similar.

**Comment by khushal-banks** [comment]
@jgabaut, I have opened this as a separate issue #10 . Can you copy-paste your comments there as well? I would have to research about all this a little more. Let's carry on this conversation another time.

**Comment by jgabaut** [comment]
I'm watching the issue so I should get a notification once you update this issue with new updates on the wanted interface to support passing color.

Thanks for your collaboration, looking forward to messing with the color handling implementation and maybe the compatibility layer between the signatures! 😄

**Comment by jgabaut** [comment]
I checked out the reference repo and it seems the approach they took is what's most coherent with the functionality selection style of this library.

What I mean is that, if I got it right, the most important thing would be having a `DO_COLOR` macro define of some sort that conditionally turns off all color handling and goes to the default current implementation of the core print call.

I checked out the stub for color but will need some more time to get a pr in, should be doable later in the night.

**Comment by khushal-banks** [comment]
Yes, reference repo is using a macro to control this at compile-time. But we want to control it at run-time.
I added color-support as per our discussion in latest commit.

Submit a PR if you want a different type of implementation.

**Comment by jgabaut** [comment]
Wonderful, it seems you got it done faster than I could. Nice!

**Comment by khushal-banks** [comment]
I got a basic color support working. If you want to improve it, go ahead. I will merge your PR.
